defaults:
  - data
  - model/teacher
  - model/student
  - distill
  - train
  - _self_

# Output directory for logs and artifacts
output_dir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d_%H-%M-%S}

# Paths to save models and artifacts
paths:
  checkpoints: ${output_dir}/checkpoints
  teacher_model: ${paths.checkpoints}/teacher.ckpt
  student_model: ${output_dir}/artifacts/student.pkl
  tokenizer: ${output_dir}/artifacts/tokenizer
  vectorizer: ${output_dir}/artifacts/vectorizer.pkl
  distill_data: ${output_dir}/artifacts/distill_train.parquet
  evaluation_report: ${output_dir}/evaluation_report.json

# Logging
logging:
  tensorboard_log_dir: ${output_dir}/tensorboard

# Model Registry configuration  
registry:
  enabled: true  # Enable model registry
  dir: ${hydra:runtime.cwd}/model_registry  # Path to the registry directory
  model_id: null  # Auto-generate model ID
  description: null  # Auto-generate description
  export_best: true  # Export best models to inference directory
  inference_dir: ${hydra:runtime.cwd}/inference/models  # Path to the inference directory 