paths:
  # Data paths
  data_dir: "data"
  raw_data: "data/raw"
  processed_data: "data/processed"
  
  # Model paths
  teacher_model: "outputs/teacher/checkpoints/teacher.ckpt"
  student_model: "outputs/student/student.pkl"
  tokenizer: "outputs/tokenizer/tokenizer.json"
  
  # Checkpoint paths
  checkpoints: "outputs/teacher/checkpoints"
  
  # Evaluation paths
  evaluation:
    report: "outputs/evaluation/evaluation_report.json"
  
  # Benchmark paths
  benchmark:
    report: "outputs/benchmark/benchmark_results.csv"
    best_configs: "outputs/benchmark/best_configs.json" 